name: vsc_quill_delta_to_html
description: A robust Quill Delta to HTML converter. This is a complete port of the popular quill-delta-to-html Typescript/Javascript package to Dart.
version: 1.0.1+1
homepage: https://github.com/VisualSystemsCorp/vsc_quill_delta_to_html

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  html_unescape: ^2.0.0
  collection: ^1.16.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
